name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: DeterminateSystems/nix-installer-action@v14
      
      - name: Build server
        run: nix build .#server
      
      - name: Test server starts
        run: |
          nix run .#server &
          SERVER_PID=$!
          sleep 2
          curl -f http://localhost:9000 || (kill $SERVER_PID; exit 1)
          kill $SERVER_PID

      - name: Install gh CLI
        if: github.event_name == 'push'
        run: |
          type gh || (curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y)
      
      - name: Create PR in configs repo
        if: github.event_name == 'push'
        env:
          GH_TOKEN: ${{ secrets.INFRA_TOKEN }}
        run: |
          sha="${GITHUB_SHA}"
          echo "Creating PR in configs repo to update hello-http to SHA: $sha"
          
          # Clone configs repo using token
          git clone "https://x-access-token:${GH_TOKEN}@github.com/justinmoon/configs.git" /tmp/configs
          cd /tmp/configs
          
          # Configure git
          git config user.name 'hello-http-bot'
          git config user.email 'bot@users.noreply.github.com'
          
          # Create branch for the update
          branch="bump-hello-http-${sha:0:7}"
          git checkout -b "$branch"
          
          # Update flake.lock
          nix flake lock \
            --override-input hello-http "github:justinmoon/hello-http/${sha}" \
            --update-input hello-http
          
          # Commit and push
          git add flake.lock
          git commit -m "bump: hello-http to ${sha:0:7}" || exit 0  # Exit if no changes
          
          # Push using GitHub token
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/justinmoon/configs.git"
          git push origin "$branch"
          
          # Create PR using gh CLI
          cat > /tmp/pr-body.md << EOF
          Automated PR to update hello-http to commit ${sha}
          
          This PR was automatically created by the hello-http CI workflow.
          
          Changes:
          - Updated flake.lock to use hello-http@${sha}
          
          After merging, the GitOps deployment will automatically apply this update.
          EOF
          
          gh pr create \
            --repo justinmoon/configs \
            --base master \
            --head "$branch" \
            --title "Bump hello-http to ${sha:0:7}" \
            --body-file /tmp/pr-body.md